function [GCS_mean_avgp,GCS_vec] = geomSim(tf,ts,opt,simulation_path)

%Multi-Body Simulation
out = sim(simulation_path,'StartTime','0','StopTime',num2str(tf),'FixedStep',num2str(ts));
%Extraction of Distances in 3 configurations:
%Average Posture
d_avg_p = [out.d_thb.Data(1),out.d_idx.Data(1),out.d_mid.Data(1),out.d_rig.Data(1),out.d_lit.Data(1),...
           out.d_thb_dip.Data(1),out.d_idx_dip.Data(1),out.d_mid_dip.Data(1),out.d_rig_dip.Data(1),out.d_lit_dip.Data(1),...
           out.d_thb_pip.Data(1),out.d_idx_pip.Data(1),out.d_mid_pip.Data(1),out.d_rig_pip.Data(1),out.d_lit_pip.Data(1)];

if opt == 1
    %Maximum Posture
    d_max_p = [out.d_thb.Data(find(out.d_thb.Time == tf/4)),...
        out.d_idx.Data(find(out.d_idx.Time == tf/4)),...
        out.d_mid.Data(find(out.d_mid.Time == tf/4)),...
        out.d_rig.Data(find(out.d_rig.Time == tf/4)),...
        out.d_lit.Data(find(out.d_lit.Time == tf/4)),...
        out.d_thb_dip.Data(find(out.d_thb_dip.Time == tf/4)),...
        out.d_idx_dip.Data(find(out.d_idx_dip.Time == tf/4)),...
        out.d_mid_dip.Data(find(out.d_mid_dip.Time == tf/4)),...
        out.d_rig_dip.Data(find(out.d_rig_dip.Time == tf/4)),...
        out.d_lit_dip.Data(find(out.d_lit_dip.Time == tf/4)),...
        out.d_thb_pip.Data(find(out.d_thb_pip.Time == tf/4)),...
        out.d_idx_pip.Data(find(out.d_idx_pip.Time == tf/4)),...
        out.d_mid_pip.Data(find(out.d_mid_pip.Time == tf/4)),...
        out.d_rig_pip.Data(find(out.d_rig_pip.Time == tf/4)),...
        out.d_lit_pip.Data(find(out.d_lit_pip.Time == tf/4))];
    %Minimum Posture
    d_min_p = [out.d_thb.Data(find(out.d_thb.Time == 3*tf/4)),...
        out.d_idx.Data(find(out.d_idx.Time == 3*tf/4)),...
        out.d_mid.Data(find(out.d_mid.Time == 3*tf/4)),...
        out.d_rig.Data(find(out.d_rig.Time == 3*tf/4)),...
        out.d_lit.Data(find(out.d_lit.Time == 3*tf/4)),...
        out.d_thb_dip.Data(find(out.d_thb_dip.Time == 3*tf/4)),...
        out.d_idx_dip.Data(find(out.d_idx_dip.Time == 3*tf/4)),...
        out.d_mid_dip.Data(find(out.d_mid_dip.Time == 3*tf/4)),...
        out.d_rig_dip.Data(find(out.d_rig_dip.Time == 3*tf/4)),...
        out.d_lit_dip.Data(find(out.d_lit_dip.Time == 3*tf/4)),...
        out.d_thb_pip.Data(find(out.d_thb_pip.Time == 3*tf/4)),...
        out.d_idx_pip.Data(find(out.d_idx_pip.Time == 3*tf/4)),...
        out.d_mid_pip.Data(find(out.d_mid_pip.Time == 3*tf/4)),...
        out.d_rig_pip.Data(find(out.d_rig_pip.Time == 3*tf/4)),...
        out.d_lit_pip.Data(find(out.d_lit_pip.Time == 3*tf/4))];
else
    %Maximum Posture
    d_max_p = [out.d_thb.Data(3),...
        out.d_idx.Data(3),...
        out.d_mid.Data(3),...
        out.d_rig.Data(3),...
        out.d_lit.Data(3),...
        out.d_thb_dip.Data(3),...
        out.d_idx_dip.Data(3),...
        out.d_mid_dip.Data(3),...
        out.d_rig_dip.Data(3),...
        out.d_lit_dip.Data(3),...
        out.d_thb_pip.Data(3),...
        out.d_idx_pip.Data(3),...
        out.d_mid_pip.Data(3),...
        out.d_rig_pip.Data(3),...
        out.d_lit_pip.Data(3)];
    %Minimum Posture
    d_min_p = [out.d_thb.Data(4),...
        out.d_idx.Data(4),...
        out.d_mid.Data(4),...
        out.d_rig.Data(4),...
        out.d_lit.Data(4),...
        out.d_thb_dip.Data(4),...
        out.d_idx_dip.Data(4),...
        out.d_mid_dip.Data(4),...
        out.d_rig_dip.Data(4),...
        out.d_lit_dip.Data(4),...
        out.d_thb_pip.Data(4),...
        out.d_idx_pip.Data(4),...
        out.d_mid_pip.Data(4),...
        out.d_rig_pip.Data(4),...
        out.d_lit_pip.Data(4)];
end
[GCS_mean_avgp,GCS_vec] = GCS(d_avg_p,d_max_p,d_min_p,1); %0 for no plot
end